### ISSUE TITLE
Replying a message from freqtrade repository

### ISSUE THREAD

**Issue by criadoperez** [nathanrhoda/corda-hello-world#1]
Hello @nathanrhoda,

I wanted to contact you regarding the message you posted to me in 

https://github.com/freqtrade/freqtrade/issues/1710#issuecomment-846389917_

where you stated: "@criadoperez  Im in just wrapping up a few side projects but lets discuss how we can approach this."

Sorry to create this as an issue, but I just didn't know any other way to contact you directly, and freqtrade asked to continue our conversation elsewhere.

I just wanted to let you know that I finally put back together the arbitrage software I developed back in 2017/2018.

The project is here: https://gitlab.com/criadoperez/mercury

It trades automatically in different exchanges around the world at the same time. Anyway, if you are interested let me know. If not, don't worry I won't bother you again.

Take care,

Alejandro.

**Comment by nathanrhoda** [comment]
Hi  @criadoperez 

Thanks for this will definitely have a look. 
This is my email address nathan.rhoda@gmail.com lets continue this discussion via email.

Need another 3 weeks on my current projects then all my focus will be going into arbing and flashloans so keen to dig into what you have already built.
